(require :asdf)

(defvar *input* (uiop:read-file-lines "input"))

(defun ans1 (*input*)
    (apply #'+ (mapcar (lambda (l)
                (let* ((nums (mapcar (lambda (x) (- (char-int x) 48)) (coerce l 'list)))
                       (n (length nums))
                       (i 1)
                       (maxi 0)
                       (j (- n 2))
                       (maxj (1- n)))
                    (loop while (< i (1- n))
                        do 
                        (when (> (nth i nums) (nth maxi nums))
                            (setf maxi i))
                        (incf i)
                    )
                    (loop while (> j maxi)
                        do 
                        (when (> (nth j nums) (nth maxj nums))
                            (setf maxj j))
                        (decf j)
                    )
                    (+ (* 10 (nth maxi nums)) (nth maxj nums))
                ))
    *input*))
)

(defun ans2 (*input*)
    (apply #'+ (mapcar (lambda (l)
                (let* ((nums (mapcar (lambda (x) (- (char-int x) 48)) (coerce l 'list)))
                        (n (length nums))
                        (ans 0)
                        (i 0)
                        (j 1)
                        (maxj 0))
                        (loop while (< i 12)
                        do 
                            (loop while (< j (- n (- 11 i)))
                                do 
                                (when (> (nth j nums) (nth maxj nums))
                                    (setf maxj j)
                                )
                                (incf j)
                            )
                            (incf ans (* (expt 10 (- 11 i)) (nth maxj nums)))
                            (setf j (1+ (incf maxj)))
                            (incf i)
                        )
                        ans
                ))
    *input*))
)

(print (ans1 *input*))
(print (ans2 *input*))
(terpri)