(require :asdf)

(defvar *input* (uiop:read-file-lines "input"))

(defun ans1 (*input*)
  (let* ((g (coerce *input* 'vector)) (n (length g)) (m (length (elt g 0))) (s 0))
    (dotimes (i n)
      (dotimes (j m)
        (let ((c (char (elt g i) j)) (nei 0))
          (when (char= c #\@)
            (loop for di in '(-1 0 1)
              do (loop for dj in '(-1 0 1)
                do (when 
                    (and (>= (+ di i) 0) (< (+ di i) n)
                    (>= (+ dj j) 0) (< (+ dj j) m)
                    (char= (char (elt g (+ di i)) (+ dj j)) #\@))
                    (incf nei)
                    )
                  )
            )
            (when (< nei 5)
              (incf s)
            )
          )
        )
      )
    )
    s
  )
)

(defun ans2 (*input*)
  (let* 
    ((g (coerce (mapcar (lambda (x) (coerce (mapcar (lambda (y) (if (char= y #\@) 1 0)) (coerce x 'list)) 'vector)) *input*) 'vector))
    (n (length g))
    (m (length (elt g 0)))
    (papers 
      (loop for i below n
      append (loop for j below m
        when (= (elt (elt g i) j) 1)
        collect (list i j))
      )
    )
    (s 0))
    (let ((movable (list)))
      (loop
        (loop for (i j) in papers
          do (let ((c (elt (elt g i) j)) (nei 0))
            (when (= c 1)
              (loop for di in '(-1 0 1)
                do (loop for dj in '(-1 0 1)
                  do (when 
                      (and (>= (+ di i) 0) (< (+ di i) n)
                      (>= (+ dj j) 0) (< (+ dj j) m)
                      (= (elt (elt g (+ di i)) (+ dj j)) 1))
                      (incf nei)
                      )
                    )
              )
              (when (< nei 5)
                (push (list i j) movable)
              )
            )
          )
        )
        (loop for (i j) in movable
          do (setf (elt (elt g i) j) 0)
            (setf papers (remove (list i j) papers))
        )
        (when (zerop (length movable))
          (return s)
        )
        (incf s (length movable))
        (setf movable (list))
      )
    )
  )
)

(print (time (ans1 *input*)))
(print (time (ans2 *input*)))
(terpri)